// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ClientHello implements flatbuffers.IUnpackableObject<ClientHelloT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientHello {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientHello(bb:flatbuffers.ByteBuffer, obj?:ClientHello):ClientHello {
  return (obj || new ClientHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientHello(bb:flatbuffers.ByteBuffer, obj?:ClientHello):ClientHello {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

protocolVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

sessionToken():string|null
sessionToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sessionToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

connectionId():string|null
connectionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
connectionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

build():string|null
build(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
build(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nickname():string|null
nickname(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nickname(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

characterId():string|null
characterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
characterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startClientHello(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addProtocolVersion(builder:flatbuffers.Builder, protocolVersion:number) {
  builder.addFieldInt16(0, protocolVersion, 0);
}

static addSessionToken(builder:flatbuffers.Builder, sessionTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sessionTokenOffset, 0);
}

static addConnectionId(builder:flatbuffers.Builder, connectionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, connectionIdOffset, 0);
}

static addBuild(builder:flatbuffers.Builder, buildOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, buildOffset, 0);
}

static addNickname(builder:flatbuffers.Builder, nicknameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, nicknameOffset, 0);
}

static addCharacterId(builder:flatbuffers.Builder, characterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, characterIdOffset, 0);
}

static endClientHello(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClientHello(builder:flatbuffers.Builder, protocolVersion:number, sessionTokenOffset:flatbuffers.Offset, connectionIdOffset:flatbuffers.Offset, buildOffset:flatbuffers.Offset, nicknameOffset:flatbuffers.Offset, characterIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientHello.startClientHello(builder);
  ClientHello.addProtocolVersion(builder, protocolVersion);
  ClientHello.addSessionToken(builder, sessionTokenOffset);
  ClientHello.addConnectionId(builder, connectionIdOffset);
  ClientHello.addBuild(builder, buildOffset);
  ClientHello.addNickname(builder, nicknameOffset);
  ClientHello.addCharacterId(builder, characterIdOffset);
  return ClientHello.endClientHello(builder);
}

unpack(): ClientHelloT {
  return new ClientHelloT(
    this.protocolVersion(),
    this.sessionToken(),
    this.connectionId(),
    this.build(),
    this.nickname(),
    this.characterId()
  );
}


unpackTo(_o: ClientHelloT): void {
  _o.protocolVersion = this.protocolVersion();
  _o.sessionToken = this.sessionToken();
  _o.connectionId = this.connectionId();
  _o.build = this.build();
  _o.nickname = this.nickname();
  _o.characterId = this.characterId();
}
}

export class ClientHelloT implements flatbuffers.IGeneratedObject {
constructor(
  public protocolVersion: number = 0,
  public sessionToken: string|Uint8Array|null = null,
  public connectionId: string|Uint8Array|null = null,
  public build: string|Uint8Array|null = null,
  public nickname: string|Uint8Array|null = null,
  public characterId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const sessionToken = (this.sessionToken !== null ? builder.createString(this.sessionToken!) : 0);
  const connectionId = (this.connectionId !== null ? builder.createString(this.connectionId!) : 0);
  const build = (this.build !== null ? builder.createString(this.build!) : 0);
  const nickname = (this.nickname !== null ? builder.createString(this.nickname!) : 0);
  const characterId = (this.characterId !== null ? builder.createString(this.characterId!) : 0);

  return ClientHello.createClientHello(builder,
    this.protocolVersion,
    sessionToken,
    connectionId,
    build,
    nickname,
    characterId
  );
}
}
