// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Disconnect implements flatbuffers.IUnpackableObject<DisconnectT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Disconnect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDisconnect(bb:flatbuffers.ByteBuffer, obj?:Disconnect):Disconnect {
  return (obj || new Disconnect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDisconnect(bb:flatbuffers.ByteBuffer, obj?:Disconnect):Disconnect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Disconnect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():string|null
code(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
code(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDisconnect(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, codeOffset, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endDisconnect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDisconnect(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  Disconnect.startDisconnect(builder);
  Disconnect.addCode(builder, codeOffset);
  Disconnect.addMessage(builder, messageOffset);
  return Disconnect.endDisconnect(builder);
}

unpack(): DisconnectT {
  return new DisconnectT(
    this.code(),
    this.message()
  );
}


unpackTo(_o: DisconnectT): void {
  _o.code = this.code();
  _o.message = this.message();
}
}

export class DisconnectT implements flatbuffers.IGeneratedObject {
constructor(
  public code: string|Uint8Array|null = null,
  public message: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const code = (this.code !== null ? builder.createString(this.code!) : 0);
  const message = (this.message !== null ? builder.createString(this.message!) : 0);

  return Disconnect.createDisconnect(builder,
    code,
    message
  );
}
}
