// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FireWeaponRequest implements flatbuffers.IUnpackableObject<FireWeaponRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FireWeaponRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFireWeaponRequest(bb:flatbuffers.ByteBuffer, obj?:FireWeaponRequest):FireWeaponRequest {
  return (obj || new FireWeaponRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFireWeaponRequest(bb:flatbuffers.ByteBuffer, obj?:FireWeaponRequest):FireWeaponRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FireWeaponRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientShotSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

weaponId():string|null
weaponId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weaponId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

originX():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

originY():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

originZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dirX():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dirY():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dirZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startFireWeaponRequest(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addClientShotSeq(builder:flatbuffers.Builder, clientShotSeq:number) {
  builder.addFieldInt32(0, clientShotSeq, 0);
}

static addWeaponId(builder:flatbuffers.Builder, weaponIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, weaponIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt32(2, weaponSlot, 0);
}

static addOriginX(builder:flatbuffers.Builder, originX:number) {
  builder.addFieldFloat64(3, originX, 0.0);
}

static addOriginY(builder:flatbuffers.Builder, originY:number) {
  builder.addFieldFloat64(4, originY, 0.0);
}

static addOriginZ(builder:flatbuffers.Builder, originZ:number) {
  builder.addFieldFloat64(5, originZ, 0.0);
}

static addDirX(builder:flatbuffers.Builder, dirX:number) {
  builder.addFieldFloat64(6, dirX, 0.0);
}

static addDirY(builder:flatbuffers.Builder, dirY:number) {
  builder.addFieldFloat64(7, dirY, 0.0);
}

static addDirZ(builder:flatbuffers.Builder, dirZ:number) {
  builder.addFieldFloat64(8, dirZ, 0.0);
}

static endFireWeaponRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFireWeaponRequest(builder:flatbuffers.Builder, clientShotSeq:number, weaponIdOffset:flatbuffers.Offset, weaponSlot:number, originX:number, originY:number, originZ:number, dirX:number, dirY:number, dirZ:number):flatbuffers.Offset {
  FireWeaponRequest.startFireWeaponRequest(builder);
  FireWeaponRequest.addClientShotSeq(builder, clientShotSeq);
  FireWeaponRequest.addWeaponId(builder, weaponIdOffset);
  FireWeaponRequest.addWeaponSlot(builder, weaponSlot);
  FireWeaponRequest.addOriginX(builder, originX);
  FireWeaponRequest.addOriginY(builder, originY);
  FireWeaponRequest.addOriginZ(builder, originZ);
  FireWeaponRequest.addDirX(builder, dirX);
  FireWeaponRequest.addDirY(builder, dirY);
  FireWeaponRequest.addDirZ(builder, dirZ);
  return FireWeaponRequest.endFireWeaponRequest(builder);
}

unpack(): FireWeaponRequestT {
  return new FireWeaponRequestT(
    this.clientShotSeq(),
    this.weaponId(),
    this.weaponSlot(),
    this.originX(),
    this.originY(),
    this.originZ(),
    this.dirX(),
    this.dirY(),
    this.dirZ()
  );
}


unpackTo(_o: FireWeaponRequestT): void {
  _o.clientShotSeq = this.clientShotSeq();
  _o.weaponId = this.weaponId();
  _o.weaponSlot = this.weaponSlot();
  _o.originX = this.originX();
  _o.originY = this.originY();
  _o.originZ = this.originZ();
  _o.dirX = this.dirX();
  _o.dirY = this.dirY();
  _o.dirZ = this.dirZ();
}
}

export class FireWeaponRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public clientShotSeq: number = 0,
  public weaponId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public originX: number = 0.0,
  public originY: number = 0.0,
  public originZ: number = 0.0,
  public dirX: number = 0.0,
  public dirY: number = 0.0,
  public dirZ: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const weaponId = (this.weaponId !== null ? builder.createString(this.weaponId!) : 0);

  return FireWeaponRequest.createFireWeaponRequest(builder,
    this.clientShotSeq,
    weaponId,
    this.weaponSlot,
    this.originX,
    this.originY,
    this.originZ,
    this.dirX,
    this.dirY,
    this.dirZ
  );
}
}
