// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { HitConfirmedFx, HitConfirmedFxT } from '../../afps/protocol/hit-confirmed-fx.js';
import { NearMissFx, NearMissFxT } from '../../afps/protocol/near-miss-fx.js';
import { OverheatFx, OverheatFxT } from '../../afps/protocol/overheat-fx.js';
import { PickupSpawnedFx, PickupSpawnedFxT } from '../../afps/protocol/pickup-spawned-fx.js';
import { PickupTakenFx, PickupTakenFxT } from '../../afps/protocol/pickup-taken-fx.js';
import { ProjectileImpactFx, ProjectileImpactFxT } from '../../afps/protocol/projectile-impact-fx.js';
import { ProjectileRemoveFx, ProjectileRemoveFxT } from '../../afps/protocol/projectile-remove-fx.js';
import { ProjectileSpawnFx, ProjectileSpawnFxT } from '../../afps/protocol/projectile-spawn-fx.js';
import { ReloadFx, ReloadFxT } from '../../afps/protocol/reload-fx.js';
import { ShotFiredFx, ShotFiredFxT } from '../../afps/protocol/shot-fired-fx.js';
import { ShotTraceFx, ShotTraceFxT } from '../../afps/protocol/shot-trace-fx.js';
import { VentFx, VentFxT } from '../../afps/protocol/vent-fx.js';


export enum FxEvent {
  NONE = 0,
  ShotFiredFx = 1,
  ShotTraceFx = 2,
  ReloadFx = 3,
  NearMissFx = 4,
  OverheatFx = 5,
  VentFx = 6,
  HitConfirmedFx = 7,
  ProjectileSpawnFx = 8,
  ProjectileImpactFx = 9,
  ProjectileRemoveFx = 10,
  PickupSpawnedFx = 11,
  PickupTakenFx = 12
}

export function unionToFxEvent(
  type: FxEvent,
  accessor: (obj:HitConfirmedFx|NearMissFx|OverheatFx|PickupSpawnedFx|PickupTakenFx|ProjectileImpactFx|ProjectileRemoveFx|ProjectileSpawnFx|ReloadFx|ShotFiredFx|ShotTraceFx|VentFx) => HitConfirmedFx|NearMissFx|OverheatFx|PickupSpawnedFx|PickupTakenFx|ProjectileImpactFx|ProjectileRemoveFx|ProjectileSpawnFx|ReloadFx|ShotFiredFx|ShotTraceFx|VentFx|null
): HitConfirmedFx|NearMissFx|OverheatFx|PickupSpawnedFx|PickupTakenFx|ProjectileImpactFx|ProjectileRemoveFx|ProjectileSpawnFx|ReloadFx|ShotFiredFx|ShotTraceFx|VentFx|null {
  switch(FxEvent[type]) {
    case 'NONE': return null; 
    case 'ShotFiredFx': return accessor(new ShotFiredFx())! as ShotFiredFx;
    case 'ShotTraceFx': return accessor(new ShotTraceFx())! as ShotTraceFx;
    case 'ReloadFx': return accessor(new ReloadFx())! as ReloadFx;
    case 'NearMissFx': return accessor(new NearMissFx())! as NearMissFx;
    case 'OverheatFx': return accessor(new OverheatFx())! as OverheatFx;
    case 'VentFx': return accessor(new VentFx())! as VentFx;
    case 'HitConfirmedFx': return accessor(new HitConfirmedFx())! as HitConfirmedFx;
    case 'ProjectileSpawnFx': return accessor(new ProjectileSpawnFx())! as ProjectileSpawnFx;
    case 'ProjectileImpactFx': return accessor(new ProjectileImpactFx())! as ProjectileImpactFx;
    case 'ProjectileRemoveFx': return accessor(new ProjectileRemoveFx())! as ProjectileRemoveFx;
    case 'PickupSpawnedFx': return accessor(new PickupSpawnedFx())! as PickupSpawnedFx;
    case 'PickupTakenFx': return accessor(new PickupTakenFx())! as PickupTakenFx;
    default: return null;
  }
}

export function unionListToFxEvent(
  type: FxEvent, 
  accessor: (index: number, obj:HitConfirmedFx|NearMissFx|OverheatFx|PickupSpawnedFx|PickupTakenFx|ProjectileImpactFx|ProjectileRemoveFx|ProjectileSpawnFx|ReloadFx|ShotFiredFx|ShotTraceFx|VentFx) => HitConfirmedFx|NearMissFx|OverheatFx|PickupSpawnedFx|PickupTakenFx|ProjectileImpactFx|ProjectileRemoveFx|ProjectileSpawnFx|ReloadFx|ShotFiredFx|ShotTraceFx|VentFx|null, 
  index: number
): HitConfirmedFx|NearMissFx|OverheatFx|PickupSpawnedFx|PickupTakenFx|ProjectileImpactFx|ProjectileRemoveFx|ProjectileSpawnFx|ReloadFx|ShotFiredFx|ShotTraceFx|VentFx|null {
  switch(FxEvent[type]) {
    case 'NONE': return null; 
    case 'ShotFiredFx': return accessor(index, new ShotFiredFx())! as ShotFiredFx;
    case 'ShotTraceFx': return accessor(index, new ShotTraceFx())! as ShotTraceFx;
    case 'ReloadFx': return accessor(index, new ReloadFx())! as ReloadFx;
    case 'NearMissFx': return accessor(index, new NearMissFx())! as NearMissFx;
    case 'OverheatFx': return accessor(index, new OverheatFx())! as OverheatFx;
    case 'VentFx': return accessor(index, new VentFx())! as VentFx;
    case 'HitConfirmedFx': return accessor(index, new HitConfirmedFx())! as HitConfirmedFx;
    case 'ProjectileSpawnFx': return accessor(index, new ProjectileSpawnFx())! as ProjectileSpawnFx;
    case 'ProjectileImpactFx': return accessor(index, new ProjectileImpactFx())! as ProjectileImpactFx;
    case 'ProjectileRemoveFx': return accessor(index, new ProjectileRemoveFx())! as ProjectileRemoveFx;
    case 'PickupSpawnedFx': return accessor(index, new PickupSpawnedFx())! as PickupSpawnedFx;
    case 'PickupTakenFx': return accessor(index, new PickupTakenFx())! as PickupTakenFx;
    default: return null;
  }
}
