// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GameEventType } from '../../afps/protocol/game-event-type.js';


export class GameEvent implements flatbuffers.IUnpackableObject<GameEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameEvent(bb:flatbuffers.ByteBuffer, obj?:GameEvent):GameEvent {
  return (obj || new GameEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameEvent(bb:flatbuffers.ByteBuffer, obj?:GameEvent):GameEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventType():GameEventType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : GameEventType.HitConfirmed;
}

targetId():string|null
targetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ownerId():string|null
ownerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ownerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

projectileId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

damage():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

killed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

posX():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

posY():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

posZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

velX():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

velY():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

velZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

ttl():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startGameEvent(builder:flatbuffers.Builder) {
  builder.startObject(13);
}

static addEventType(builder:flatbuffers.Builder, eventType:GameEventType) {
  builder.addFieldInt8(0, eventType, GameEventType.HitConfirmed);
}

static addTargetId(builder:flatbuffers.Builder, targetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, targetIdOffset, 0);
}

static addOwnerId(builder:flatbuffers.Builder, ownerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, ownerIdOffset, 0);
}

static addProjectileId(builder:flatbuffers.Builder, projectileId:number) {
  builder.addFieldInt32(3, projectileId, 0);
}

static addDamage(builder:flatbuffers.Builder, damage:number) {
  builder.addFieldFloat64(4, damage, 0.0);
}

static addKilled(builder:flatbuffers.Builder, killed:boolean) {
  builder.addFieldInt8(5, +killed, +false);
}

static addPosX(builder:flatbuffers.Builder, posX:number) {
  builder.addFieldFloat64(6, posX, 0.0);
}

static addPosY(builder:flatbuffers.Builder, posY:number) {
  builder.addFieldFloat64(7, posY, 0.0);
}

static addPosZ(builder:flatbuffers.Builder, posZ:number) {
  builder.addFieldFloat64(8, posZ, 0.0);
}

static addVelX(builder:flatbuffers.Builder, velX:number) {
  builder.addFieldFloat64(9, velX, 0.0);
}

static addVelY(builder:flatbuffers.Builder, velY:number) {
  builder.addFieldFloat64(10, velY, 0.0);
}

static addVelZ(builder:flatbuffers.Builder, velZ:number) {
  builder.addFieldFloat64(11, velZ, 0.0);
}

static addTtl(builder:flatbuffers.Builder, ttl:number) {
  builder.addFieldFloat64(12, ttl, 0.0);
}

static endGameEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameEvent(builder:flatbuffers.Builder, eventType:GameEventType, targetIdOffset:flatbuffers.Offset, ownerIdOffset:flatbuffers.Offset, projectileId:number, damage:number, killed:boolean, posX:number, posY:number, posZ:number, velX:number, velY:number, velZ:number, ttl:number):flatbuffers.Offset {
  GameEvent.startGameEvent(builder);
  GameEvent.addEventType(builder, eventType);
  GameEvent.addTargetId(builder, targetIdOffset);
  GameEvent.addOwnerId(builder, ownerIdOffset);
  GameEvent.addProjectileId(builder, projectileId);
  GameEvent.addDamage(builder, damage);
  GameEvent.addKilled(builder, killed);
  GameEvent.addPosX(builder, posX);
  GameEvent.addPosY(builder, posY);
  GameEvent.addPosZ(builder, posZ);
  GameEvent.addVelX(builder, velX);
  GameEvent.addVelY(builder, velY);
  GameEvent.addVelZ(builder, velZ);
  GameEvent.addTtl(builder, ttl);
  return GameEvent.endGameEvent(builder);
}

unpack(): GameEventT {
  return new GameEventT(
    this.eventType(),
    this.targetId(),
    this.ownerId(),
    this.projectileId(),
    this.damage(),
    this.killed(),
    this.posX(),
    this.posY(),
    this.posZ(),
    this.velX(),
    this.velY(),
    this.velZ(),
    this.ttl()
  );
}


unpackTo(_o: GameEventT): void {
  _o.eventType = this.eventType();
  _o.targetId = this.targetId();
  _o.ownerId = this.ownerId();
  _o.projectileId = this.projectileId();
  _o.damage = this.damage();
  _o.killed = this.killed();
  _o.posX = this.posX();
  _o.posY = this.posY();
  _o.posZ = this.posZ();
  _o.velX = this.velX();
  _o.velY = this.velY();
  _o.velZ = this.velZ();
  _o.ttl = this.ttl();
}
}

export class GameEventT implements flatbuffers.IGeneratedObject {
constructor(
  public eventType: GameEventType = GameEventType.HitConfirmed,
  public targetId: string|Uint8Array|null = null,
  public ownerId: string|Uint8Array|null = null,
  public projectileId: number = 0,
  public damage: number = 0.0,
  public killed: boolean = false,
  public posX: number = 0.0,
  public posY: number = 0.0,
  public posZ: number = 0.0,
  public velX: number = 0.0,
  public velY: number = 0.0,
  public velZ: number = 0.0,
  public ttl: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const targetId = (this.targetId !== null ? builder.createString(this.targetId!) : 0);
  const ownerId = (this.ownerId !== null ? builder.createString(this.ownerId!) : 0);

  return GameEvent.createGameEvent(builder,
    this.eventType,
    targetId,
    ownerId,
    this.projectileId,
    this.damage,
    this.killed,
    this.posX,
    this.posY,
    this.posZ,
    this.velX,
    this.velY,
    this.velZ,
    this.ttl
  );
}
}
