// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class HitConfirmedFx implements flatbuffers.IUnpackableObject<HitConfirmedFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HitConfirmedFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHitConfirmedFx(bb:flatbuffers.ByteBuffer, obj?:HitConfirmedFx):HitConfirmedFx {
  return (obj || new HitConfirmedFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHitConfirmedFx(bb:flatbuffers.ByteBuffer, obj?:HitConfirmedFx):HitConfirmedFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HitConfirmedFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

targetId():string|null
targetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

damage():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

killed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startHitConfirmedFx(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTargetId(builder:flatbuffers.Builder, targetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, targetIdOffset, 0);
}

static addDamage(builder:flatbuffers.Builder, damage:number) {
  builder.addFieldFloat64(1, damage, 0.0);
}

static addKilled(builder:flatbuffers.Builder, killed:boolean) {
  builder.addFieldInt8(2, +killed, +false);
}

static endHitConfirmedFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHitConfirmedFx(builder:flatbuffers.Builder, targetIdOffset:flatbuffers.Offset, damage:number, killed:boolean):flatbuffers.Offset {
  HitConfirmedFx.startHitConfirmedFx(builder);
  HitConfirmedFx.addTargetId(builder, targetIdOffset);
  HitConfirmedFx.addDamage(builder, damage);
  HitConfirmedFx.addKilled(builder, killed);
  return HitConfirmedFx.endHitConfirmedFx(builder);
}

unpack(): HitConfirmedFxT {
  return new HitConfirmedFxT(
    this.targetId(),
    this.damage(),
    this.killed()
  );
}


unpackTo(_o: HitConfirmedFxT): void {
  _o.targetId = this.targetId();
  _o.damage = this.damage();
  _o.killed = this.killed();
}
}

export class HitConfirmedFxT implements flatbuffers.IGeneratedObject {
constructor(
  public targetId: string|Uint8Array|null = null,
  public damage: number = 0.0,
  public killed: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const targetId = (this.targetId !== null ? builder.createString(this.targetId!) : 0);

  return HitConfirmedFx.createHitConfirmedFx(builder,
    targetId,
    this.damage,
    this.killed
  );
}
}
