// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class InputCmd implements flatbuffers.IUnpackableObject<InputCmdT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InputCmd {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInputCmd(bb:flatbuffers.ByteBuffer, obj?:InputCmd):InputCmd {
  return (obj || new InputCmd()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInputCmd(bb:flatbuffers.ByteBuffer, obj?:InputCmd):InputCmd {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InputCmd()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

inputSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

moveX():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

moveY():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

lookDeltaX():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

lookDeltaY():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

viewYaw():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

viewPitch():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

jump():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

fire():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

ads():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

sprint():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

dash():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

grapple():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

shield():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

shockwave():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startInputCmd(builder:flatbuffers.Builder) {
  builder.startObject(16);
}

static addInputSeq(builder:flatbuffers.Builder, inputSeq:number) {
  builder.addFieldInt32(0, inputSeq, 0);
}

static addMoveX(builder:flatbuffers.Builder, moveX:number) {
  builder.addFieldFloat64(1, moveX, 0.0);
}

static addMoveY(builder:flatbuffers.Builder, moveY:number) {
  builder.addFieldFloat64(2, moveY, 0.0);
}

static addLookDeltaX(builder:flatbuffers.Builder, lookDeltaX:number) {
  builder.addFieldFloat64(3, lookDeltaX, 0.0);
}

static addLookDeltaY(builder:flatbuffers.Builder, lookDeltaY:number) {
  builder.addFieldFloat64(4, lookDeltaY, 0.0);
}

static addViewYaw(builder:flatbuffers.Builder, viewYaw:number) {
  builder.addFieldFloat64(5, viewYaw, 0.0);
}

static addViewPitch(builder:flatbuffers.Builder, viewPitch:number) {
  builder.addFieldFloat64(6, viewPitch, 0.0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt32(7, weaponSlot, 0);
}

static addJump(builder:flatbuffers.Builder, jump:boolean) {
  builder.addFieldInt8(8, +jump, +false);
}

static addFire(builder:flatbuffers.Builder, fire:boolean) {
  builder.addFieldInt8(9, +fire, +false);
}

static addAds(builder:flatbuffers.Builder, ads:boolean) {
  builder.addFieldInt8(10, +ads, +false);
}

static addSprint(builder:flatbuffers.Builder, sprint:boolean) {
  builder.addFieldInt8(11, +sprint, +false);
}

static addDash(builder:flatbuffers.Builder, dash:boolean) {
  builder.addFieldInt8(12, +dash, +false);
}

static addGrapple(builder:flatbuffers.Builder, grapple:boolean) {
  builder.addFieldInt8(13, +grapple, +false);
}

static addShield(builder:flatbuffers.Builder, shield:boolean) {
  builder.addFieldInt8(14, +shield, +false);
}

static addShockwave(builder:flatbuffers.Builder, shockwave:boolean) {
  builder.addFieldInt8(15, +shockwave, +false);
}

static endInputCmd(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInputCmd(builder:flatbuffers.Builder, inputSeq:number, moveX:number, moveY:number, lookDeltaX:number, lookDeltaY:number, viewYaw:number, viewPitch:number, weaponSlot:number, jump:boolean, fire:boolean, ads:boolean, sprint:boolean, dash:boolean, grapple:boolean, shield:boolean, shockwave:boolean):flatbuffers.Offset {
  InputCmd.startInputCmd(builder);
  InputCmd.addInputSeq(builder, inputSeq);
  InputCmd.addMoveX(builder, moveX);
  InputCmd.addMoveY(builder, moveY);
  InputCmd.addLookDeltaX(builder, lookDeltaX);
  InputCmd.addLookDeltaY(builder, lookDeltaY);
  InputCmd.addViewYaw(builder, viewYaw);
  InputCmd.addViewPitch(builder, viewPitch);
  InputCmd.addWeaponSlot(builder, weaponSlot);
  InputCmd.addJump(builder, jump);
  InputCmd.addFire(builder, fire);
  InputCmd.addAds(builder, ads);
  InputCmd.addSprint(builder, sprint);
  InputCmd.addDash(builder, dash);
  InputCmd.addGrapple(builder, grapple);
  InputCmd.addShield(builder, shield);
  InputCmd.addShockwave(builder, shockwave);
  return InputCmd.endInputCmd(builder);
}

unpack(): InputCmdT {
  return new InputCmdT(
    this.inputSeq(),
    this.moveX(),
    this.moveY(),
    this.lookDeltaX(),
    this.lookDeltaY(),
    this.viewYaw(),
    this.viewPitch(),
    this.weaponSlot(),
    this.jump(),
    this.fire(),
    this.ads(),
    this.sprint(),
    this.dash(),
    this.grapple(),
    this.shield(),
    this.shockwave()
  );
}


unpackTo(_o: InputCmdT): void {
  _o.inputSeq = this.inputSeq();
  _o.moveX = this.moveX();
  _o.moveY = this.moveY();
  _o.lookDeltaX = this.lookDeltaX();
  _o.lookDeltaY = this.lookDeltaY();
  _o.viewYaw = this.viewYaw();
  _o.viewPitch = this.viewPitch();
  _o.weaponSlot = this.weaponSlot();
  _o.jump = this.jump();
  _o.fire = this.fire();
  _o.ads = this.ads();
  _o.sprint = this.sprint();
  _o.dash = this.dash();
  _o.grapple = this.grapple();
  _o.shield = this.shield();
  _o.shockwave = this.shockwave();
}
}

export class InputCmdT implements flatbuffers.IGeneratedObject {
constructor(
  public inputSeq: number = 0,
  public moveX: number = 0.0,
  public moveY: number = 0.0,
  public lookDeltaX: number = 0.0,
  public lookDeltaY: number = 0.0,
  public viewYaw: number = 0.0,
  public viewPitch: number = 0.0,
  public weaponSlot: number = 0,
  public jump: boolean = false,
  public fire: boolean = false,
  public ads: boolean = false,
  public sprint: boolean = false,
  public dash: boolean = false,
  public grapple: boolean = false,
  public shield: boolean = false,
  public shockwave: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return InputCmd.createInputCmd(builder,
    this.inputSeq,
    this.moveX,
    this.moveY,
    this.lookDeltaX,
    this.lookDeltaY,
    this.viewYaw,
    this.viewPitch,
    this.weaponSlot,
    this.jump,
    this.fire,
    this.ads,
    this.sprint,
    this.dash,
    this.grapple,
    this.shield,
    this.shockwave
  );
}
}
