// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class JoinRequest implements flatbuffers.IUnpackableObject<JoinRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):JoinRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoinRequest(bb:flatbuffers.ByteBuffer, obj?:JoinRequest):JoinRequest {
  return (obj || new JoinRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoinRequest(bb:flatbuffers.ByteBuffer, obj?:JoinRequest):JoinRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new JoinRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nickname():string|null
nickname(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nickname(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

characterId():string|null
characterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
characterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startJoinRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNickname(builder:flatbuffers.Builder, nicknameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nicknameOffset, 0);
}

static addCharacterId(builder:flatbuffers.Builder, characterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, characterIdOffset, 0);
}

static endJoinRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoinRequest(builder:flatbuffers.Builder, nicknameOffset:flatbuffers.Offset, characterIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  JoinRequest.startJoinRequest(builder);
  JoinRequest.addNickname(builder, nicknameOffset);
  JoinRequest.addCharacterId(builder, characterIdOffset);
  return JoinRequest.endJoinRequest(builder);
}

unpack(): JoinRequestT {
  return new JoinRequestT(
    this.nickname(),
    this.characterId()
  );
}


unpackTo(_o: JoinRequestT): void {
  _o.nickname = this.nickname();
  _o.characterId = this.characterId();
}
}

export class JoinRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public nickname: string|Uint8Array|null = null,
  public characterId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const nickname = (this.nickname !== null ? builder.createString(this.nickname!) : 0);
  const characterId = (this.characterId !== null ? builder.createString(this.characterId!) : 0);

  return JoinRequest.createJoinRequest(builder,
    nickname,
    characterId
  );
}
}
