// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class JoinAccept implements flatbuffers.IUnpackableObject<JoinAcceptT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):JoinAccept {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoinAccept(bb:flatbuffers.ByteBuffer, obj?:JoinAccept):JoinAccept {
  return (obj || new JoinAccept()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoinAccept(bb:flatbuffers.ByteBuffer, obj?:JoinAccept):JoinAccept {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new JoinAccept()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientId():string|null
clientId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clientId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startJoinAccept(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addClientId(builder:flatbuffers.Builder, clientIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, clientIdOffset, 0);
}

static endJoinAccept(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoinAccept(builder:flatbuffers.Builder, clientIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  JoinAccept.startJoinAccept(builder);
  JoinAccept.addClientId(builder, clientIdOffset);
  return JoinAccept.endJoinAccept(builder);
}

unpack(): JoinAcceptT {
  return new JoinAcceptT(
    this.clientId()
  );
}


unpackTo(_o: JoinAcceptT): void {
  _o.clientId = this.clientId();
}
}

export class JoinAcceptT implements flatbuffers.IGeneratedObject {
constructor(
  public clientId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const clientId = (this.clientId !== null ? builder.createString(this.clientId!) : 0);

  return JoinAccept.createJoinAccept(builder,
    clientId
  );
}
}
