// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class KillFeedFx implements flatbuffers.IUnpackableObject<KillFeedFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):KillFeedFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsKillFeedFx(bb:flatbuffers.ByteBuffer, obj?:KillFeedFx):KillFeedFx {
  return (obj || new KillFeedFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsKillFeedFx(bb:flatbuffers.ByteBuffer, obj?:KillFeedFx):KillFeedFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new KillFeedFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

killerId():string|null
killerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
killerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

victimId():string|null
victimId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
victimId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startKillFeedFx(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKillerId(builder:flatbuffers.Builder, killerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, killerIdOffset, 0);
}

static addVictimId(builder:flatbuffers.Builder, victimIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, victimIdOffset, 0);
}

static endKillFeedFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createKillFeedFx(builder:flatbuffers.Builder, killerIdOffset:flatbuffers.Offset, victimIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  KillFeedFx.startKillFeedFx(builder);
  KillFeedFx.addKillerId(builder, killerIdOffset);
  KillFeedFx.addVictimId(builder, victimIdOffset);
  return KillFeedFx.endKillFeedFx(builder);
}

unpack(): KillFeedFxT {
  return new KillFeedFxT(
    this.killerId(),
    this.victimId()
  );
}


unpackTo(_o: KillFeedFxT): void {
  _o.killerId = this.killerId();
  _o.victimId = this.victimId();
}
}

export class KillFeedFxT implements flatbuffers.IGeneratedObject {
constructor(
  public killerId: string|Uint8Array|null = null,
  public victimId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const killerId = (this.killerId !== null ? builder.createString(this.killerId!) : 0);
  const victimId = (this.victimId !== null ? builder.createString(this.victimId!) : 0);

  return KillFeedFx.createKillFeedFx(builder,
    killerId,
    victimId
  );
}
}
