// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MessageType {
  ClientHello = 1,
  ServerHello = 2,
  JoinRequest = 3,
  JoinAccept = 4,
  InputCmd = 5,
  StateSnapshot = 6,
  StateSnapshotDelta = 7,
  GameEvent = 8,
  Ping = 9,
  Pong = 10,
  PlayerProfile = 11,
  Error = 12,
  Disconnect = 13
}
