// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class NearMissFx implements flatbuffers.IUnpackableObject<NearMissFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NearMissFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNearMissFx(bb:flatbuffers.ByteBuffer, obj?:NearMissFx):NearMissFx {
  return (obj || new NearMissFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNearMissFx(bb:flatbuffers.ByteBuffer, obj?:NearMissFx):NearMissFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NearMissFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

shotSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

strength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startNearMissFx(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addShotSeq(builder:flatbuffers.Builder, shotSeq:number) {
  builder.addFieldInt32(1, shotSeq, 0);
}

static addStrength(builder:flatbuffers.Builder, strength:number) {
  builder.addFieldInt8(2, strength, 0);
}

static endNearMissFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNearMissFx(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, shotSeq:number, strength:number):flatbuffers.Offset {
  NearMissFx.startNearMissFx(builder);
  NearMissFx.addShooterId(builder, shooterIdOffset);
  NearMissFx.addShotSeq(builder, shotSeq);
  NearMissFx.addStrength(builder, strength);
  return NearMissFx.endNearMissFx(builder);
}

unpack(): NearMissFxT {
  return new NearMissFxT(
    this.shooterId(),
    this.shotSeq(),
    this.strength()
  );
}


unpackTo(_o: NearMissFxT): void {
  _o.shooterId = this.shooterId();
  _o.shotSeq = this.shotSeq();
  _o.strength = this.strength();
}
}

export class NearMissFxT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public shotSeq: number = 0,
  public strength: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);

  return NearMissFx.createNearMissFx(builder,
    shooterId,
    this.shotSeq,
    this.strength
  );
}
}
