// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class OverheatFx implements flatbuffers.IUnpackableObject<OverheatFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OverheatFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOverheatFx(bb:flatbuffers.ByteBuffer, obj?:OverheatFx):OverheatFx {
  return (obj || new OverheatFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOverheatFx(bb:flatbuffers.ByteBuffer, obj?:OverheatFx):OverheatFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OverheatFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

heatQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startOverheatFx(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt8(1, weaponSlot, 0);
}

static addHeatQ(builder:flatbuffers.Builder, heatQ:number) {
  builder.addFieldInt16(2, heatQ, 0);
}

static endOverheatFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOverheatFx(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponSlot:number, heatQ:number):flatbuffers.Offset {
  OverheatFx.startOverheatFx(builder);
  OverheatFx.addShooterId(builder, shooterIdOffset);
  OverheatFx.addWeaponSlot(builder, weaponSlot);
  OverheatFx.addHeatQ(builder, heatQ);
  return OverheatFx.endOverheatFx(builder);
}

unpack(): OverheatFxT {
  return new OverheatFxT(
    this.shooterId(),
    this.weaponSlot(),
    this.heatQ()
  );
}


unpackTo(_o: OverheatFxT): void {
  _o.shooterId = this.shooterId();
  _o.weaponSlot = this.weaponSlot();
  _o.heatQ = this.heatQ();
}
}

export class OverheatFxT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public heatQ: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);

  return OverheatFx.createOverheatFx(builder,
    shooterId,
    this.weaponSlot,
    this.heatQ
  );
}
}
