// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PickupKind } from '../../afps/protocol/pickup-kind.js';


export class PickupSpawnedFx implements flatbuffers.IUnpackableObject<PickupSpawnedFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PickupSpawnedFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPickupSpawnedFx(bb:flatbuffers.ByteBuffer, obj?:PickupSpawnedFx):PickupSpawnedFx {
  return (obj || new PickupSpawnedFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPickupSpawnedFx(bb:flatbuffers.ByteBuffer, obj?:PickupSpawnedFx):PickupSpawnedFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PickupSpawnedFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pickupId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

kind():PickupKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PickupKind.None;
}

posXQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

posYQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

posZQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

amount():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startPickupSpawnedFx(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addPickupId(builder:flatbuffers.Builder, pickupId:number) {
  builder.addFieldInt32(0, pickupId, 0);
}

static addKind(builder:flatbuffers.Builder, kind:PickupKind) {
  builder.addFieldInt8(1, kind, PickupKind.None);
}

static addPosXQ(builder:flatbuffers.Builder, posXQ:number) {
  builder.addFieldInt16(2, posXQ, 0);
}

static addPosYQ(builder:flatbuffers.Builder, posYQ:number) {
  builder.addFieldInt16(3, posYQ, 0);
}

static addPosZQ(builder:flatbuffers.Builder, posZQ:number) {
  builder.addFieldInt16(4, posZQ, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt8(5, weaponSlot, 0);
}

static addAmount(builder:flatbuffers.Builder, amount:number) {
  builder.addFieldInt16(6, amount, 0);
}

static endPickupSpawnedFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPickupSpawnedFx(builder:flatbuffers.Builder, pickupId:number, kind:PickupKind, posXQ:number, posYQ:number, posZQ:number, weaponSlot:number, amount:number):flatbuffers.Offset {
  PickupSpawnedFx.startPickupSpawnedFx(builder);
  PickupSpawnedFx.addPickupId(builder, pickupId);
  PickupSpawnedFx.addKind(builder, kind);
  PickupSpawnedFx.addPosXQ(builder, posXQ);
  PickupSpawnedFx.addPosYQ(builder, posYQ);
  PickupSpawnedFx.addPosZQ(builder, posZQ);
  PickupSpawnedFx.addWeaponSlot(builder, weaponSlot);
  PickupSpawnedFx.addAmount(builder, amount);
  return PickupSpawnedFx.endPickupSpawnedFx(builder);
}

unpack(): PickupSpawnedFxT {
  return new PickupSpawnedFxT(
    this.pickupId(),
    this.kind(),
    this.posXQ(),
    this.posYQ(),
    this.posZQ(),
    this.weaponSlot(),
    this.amount()
  );
}


unpackTo(_o: PickupSpawnedFxT): void {
  _o.pickupId = this.pickupId();
  _o.kind = this.kind();
  _o.posXQ = this.posXQ();
  _o.posYQ = this.posYQ();
  _o.posZQ = this.posZQ();
  _o.weaponSlot = this.weaponSlot();
  _o.amount = this.amount();
}
}

export class PickupSpawnedFxT implements flatbuffers.IGeneratedObject {
constructor(
  public pickupId: number = 0,
  public kind: PickupKind = PickupKind.None,
  public posXQ: number = 0,
  public posYQ: number = 0,
  public posZQ: number = 0,
  public weaponSlot: number = 0,
  public amount: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return PickupSpawnedFx.createPickupSpawnedFx(builder,
    this.pickupId,
    this.kind,
    this.posXQ,
    this.posYQ,
    this.posZQ,
    this.weaponSlot,
    this.amount
  );
}
}
