// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class PickupTakenFx implements flatbuffers.IUnpackableObject<PickupTakenFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PickupTakenFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPickupTakenFx(bb:flatbuffers.ByteBuffer, obj?:PickupTakenFx):PickupTakenFx {
  return (obj || new PickupTakenFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPickupTakenFx(bb:flatbuffers.ByteBuffer, obj?:PickupTakenFx):PickupTakenFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PickupTakenFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pickupId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

takerId():string|null
takerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
takerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

serverTick():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPickupTakenFx(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPickupId(builder:flatbuffers.Builder, pickupId:number) {
  builder.addFieldInt32(0, pickupId, 0);
}

static addTakerId(builder:flatbuffers.Builder, takerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, takerIdOffset, 0);
}

static addServerTick(builder:flatbuffers.Builder, serverTick:number) {
  builder.addFieldInt32(2, serverTick, 0);
}

static endPickupTakenFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPickupTakenFx(builder:flatbuffers.Builder, pickupId:number, takerIdOffset:flatbuffers.Offset, serverTick:number):flatbuffers.Offset {
  PickupTakenFx.startPickupTakenFx(builder);
  PickupTakenFx.addPickupId(builder, pickupId);
  PickupTakenFx.addTakerId(builder, takerIdOffset);
  PickupTakenFx.addServerTick(builder, serverTick);
  return PickupTakenFx.endPickupTakenFx(builder);
}

unpack(): PickupTakenFxT {
  return new PickupTakenFxT(
    this.pickupId(),
    this.takerId(),
    this.serverTick()
  );
}


unpackTo(_o: PickupTakenFxT): void {
  _o.pickupId = this.pickupId();
  _o.takerId = this.takerId();
  _o.serverTick = this.serverTick();
}
}

export class PickupTakenFxT implements flatbuffers.IGeneratedObject {
constructor(
  public pickupId: number = 0,
  public takerId: string|Uint8Array|null = null,
  public serverTick: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const takerId = (this.takerId !== null ? builder.createString(this.takerId!) : 0);

  return PickupTakenFx.createPickupTakenFx(builder,
    this.pickupId,
    takerId,
    this.serverTick
  );
}
}
