// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Ping implements flatbuffers.IUnpackableObject<PingT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Ping {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPing(bb:flatbuffers.ByteBuffer, obj?:Ping):Ping {
  return (obj || new Ping()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPing(bb:flatbuffers.ByteBuffer, obj?:Ping):Ping {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Ping()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientTimeMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startPing(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addClientTimeMs(builder:flatbuffers.Builder, clientTimeMs:number) {
  builder.addFieldFloat64(0, clientTimeMs, 0.0);
}

static endPing(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPing(builder:flatbuffers.Builder, clientTimeMs:number):flatbuffers.Offset {
  Ping.startPing(builder);
  Ping.addClientTimeMs(builder, clientTimeMs);
  return Ping.endPing(builder);
}

unpack(): PingT {
  return new PingT(
    this.clientTimeMs()
  );
}


unpackTo(_o: PingT): void {
  _o.clientTimeMs = this.clientTimeMs();
}
}

export class PingT implements flatbuffers.IGeneratedObject {
constructor(
  public clientTimeMs: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Ping.createPing(builder,
    this.clientTimeMs
  );
}
}
