// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class PlayerProfile implements flatbuffers.IUnpackableObject<PlayerProfileT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerProfile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerProfile(bb:flatbuffers.ByteBuffer, obj?:PlayerProfile):PlayerProfile {
  return (obj || new PlayerProfile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerProfile(bb:flatbuffers.ByteBuffer, obj?:PlayerProfile):PlayerProfile {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerProfile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientId():string|null
clientId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clientId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nickname():string|null
nickname(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nickname(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

characterId():string|null
characterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
characterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPlayerProfile(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addClientId(builder:flatbuffers.Builder, clientIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, clientIdOffset, 0);
}

static addNickname(builder:flatbuffers.Builder, nicknameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nicknameOffset, 0);
}

static addCharacterId(builder:flatbuffers.Builder, characterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, characterIdOffset, 0);
}

static endPlayerProfile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerProfile(builder:flatbuffers.Builder, clientIdOffset:flatbuffers.Offset, nicknameOffset:flatbuffers.Offset, characterIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlayerProfile.startPlayerProfile(builder);
  PlayerProfile.addClientId(builder, clientIdOffset);
  PlayerProfile.addNickname(builder, nicknameOffset);
  PlayerProfile.addCharacterId(builder, characterIdOffset);
  return PlayerProfile.endPlayerProfile(builder);
}

unpack(): PlayerProfileT {
  return new PlayerProfileT(
    this.clientId(),
    this.nickname(),
    this.characterId()
  );
}


unpackTo(_o: PlayerProfileT): void {
  _o.clientId = this.clientId();
  _o.nickname = this.nickname();
  _o.characterId = this.characterId();
}
}

export class PlayerProfileT implements flatbuffers.IGeneratedObject {
constructor(
  public clientId: string|Uint8Array|null = null,
  public nickname: string|Uint8Array|null = null,
  public characterId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const clientId = (this.clientId !== null ? builder.createString(this.clientId!) : 0);
  const nickname = (this.nickname !== null ? builder.createString(this.nickname!) : 0);
  const characterId = (this.characterId !== null ? builder.createString(this.characterId!) : 0);

  return PlayerProfile.createPlayerProfile(builder,
    clientId,
    nickname,
    characterId
  );
}
}
