// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Pong implements flatbuffers.IUnpackableObject<PongT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Pong {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPong(bb:flatbuffers.ByteBuffer, obj?:Pong):Pong {
  return (obj || new Pong()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPong(bb:flatbuffers.ByteBuffer, obj?:Pong):Pong {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Pong()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientTimeMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startPong(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addClientTimeMs(builder:flatbuffers.Builder, clientTimeMs:number) {
  builder.addFieldFloat64(0, clientTimeMs, 0.0);
}

static endPong(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPong(builder:flatbuffers.Builder, clientTimeMs:number):flatbuffers.Offset {
  Pong.startPong(builder);
  Pong.addClientTimeMs(builder, clientTimeMs);
  return Pong.endPong(builder);
}

unpack(): PongT {
  return new PongT(
    this.clientTimeMs()
  );
}


unpackTo(_o: PongT): void {
  _o.clientTimeMs = this.clientTimeMs();
}
}

export class PongT implements flatbuffers.IGeneratedObject {
constructor(
  public clientTimeMs: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Pong.createPong(builder,
    this.clientTimeMs
  );
}
}
