// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SurfaceType } from '../../afps/protocol/surface-type.js';


export class ProjectileImpactFx implements flatbuffers.IUnpackableObject<ProjectileImpactFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProjectileImpactFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProjectileImpactFx(bb:flatbuffers.ByteBuffer, obj?:ProjectileImpactFx):ProjectileImpactFx {
  return (obj || new ProjectileImpactFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProjectileImpactFx(bb:flatbuffers.ByteBuffer, obj?:ProjectileImpactFx):ProjectileImpactFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProjectileImpactFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

projectileId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

hitWorld():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

targetId():string|null
targetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

posXQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

posYQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

posZQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

normalOctX():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

normalOctY():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

surfaceType():SurfaceType {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SurfaceType.Stone;
}

static startProjectileImpactFx(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addProjectileId(builder:flatbuffers.Builder, projectileId:number) {
  builder.addFieldInt32(0, projectileId, 0);
}

static addHitWorld(builder:flatbuffers.Builder, hitWorld:boolean) {
  builder.addFieldInt8(1, +hitWorld, +false);
}

static addTargetId(builder:flatbuffers.Builder, targetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, targetIdOffset, 0);
}

static addPosXQ(builder:flatbuffers.Builder, posXQ:number) {
  builder.addFieldInt16(3, posXQ, 0);
}

static addPosYQ(builder:flatbuffers.Builder, posYQ:number) {
  builder.addFieldInt16(4, posYQ, 0);
}

static addPosZQ(builder:flatbuffers.Builder, posZQ:number) {
  builder.addFieldInt16(5, posZQ, 0);
}

static addNormalOctX(builder:flatbuffers.Builder, normalOctX:number) {
  builder.addFieldInt16(6, normalOctX, 0);
}

static addNormalOctY(builder:flatbuffers.Builder, normalOctY:number) {
  builder.addFieldInt16(7, normalOctY, 0);
}

static addSurfaceType(builder:flatbuffers.Builder, surfaceType:SurfaceType) {
  builder.addFieldInt8(8, surfaceType, SurfaceType.Stone);
}

static endProjectileImpactFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProjectileImpactFx(builder:flatbuffers.Builder, projectileId:number, hitWorld:boolean, targetIdOffset:flatbuffers.Offset, posXQ:number, posYQ:number, posZQ:number, normalOctX:number, normalOctY:number, surfaceType:SurfaceType):flatbuffers.Offset {
  ProjectileImpactFx.startProjectileImpactFx(builder);
  ProjectileImpactFx.addProjectileId(builder, projectileId);
  ProjectileImpactFx.addHitWorld(builder, hitWorld);
  ProjectileImpactFx.addTargetId(builder, targetIdOffset);
  ProjectileImpactFx.addPosXQ(builder, posXQ);
  ProjectileImpactFx.addPosYQ(builder, posYQ);
  ProjectileImpactFx.addPosZQ(builder, posZQ);
  ProjectileImpactFx.addNormalOctX(builder, normalOctX);
  ProjectileImpactFx.addNormalOctY(builder, normalOctY);
  ProjectileImpactFx.addSurfaceType(builder, surfaceType);
  return ProjectileImpactFx.endProjectileImpactFx(builder);
}

unpack(): ProjectileImpactFxT {
  return new ProjectileImpactFxT(
    this.projectileId(),
    this.hitWorld(),
    this.targetId(),
    this.posXQ(),
    this.posYQ(),
    this.posZQ(),
    this.normalOctX(),
    this.normalOctY(),
    this.surfaceType()
  );
}


unpackTo(_o: ProjectileImpactFxT): void {
  _o.projectileId = this.projectileId();
  _o.hitWorld = this.hitWorld();
  _o.targetId = this.targetId();
  _o.posXQ = this.posXQ();
  _o.posYQ = this.posYQ();
  _o.posZQ = this.posZQ();
  _o.normalOctX = this.normalOctX();
  _o.normalOctY = this.normalOctY();
  _o.surfaceType = this.surfaceType();
}
}

export class ProjectileImpactFxT implements flatbuffers.IGeneratedObject {
constructor(
  public projectileId: number = 0,
  public hitWorld: boolean = false,
  public targetId: string|Uint8Array|null = null,
  public posXQ: number = 0,
  public posYQ: number = 0,
  public posZQ: number = 0,
  public normalOctX: number = 0,
  public normalOctY: number = 0,
  public surfaceType: SurfaceType = SurfaceType.Stone
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const targetId = (this.targetId !== null ? builder.createString(this.targetId!) : 0);

  return ProjectileImpactFx.createProjectileImpactFx(builder,
    this.projectileId,
    this.hitWorld,
    targetId,
    this.posXQ,
    this.posYQ,
    this.posZQ,
    this.normalOctX,
    this.normalOctY,
    this.surfaceType
  );
}
}
