// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ProjectileRemoveFx implements flatbuffers.IUnpackableObject<ProjectileRemoveFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProjectileRemoveFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProjectileRemoveFx(bb:flatbuffers.ByteBuffer, obj?:ProjectileRemoveFx):ProjectileRemoveFx {
  return (obj || new ProjectileRemoveFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProjectileRemoveFx(bb:flatbuffers.ByteBuffer, obj?:ProjectileRemoveFx):ProjectileRemoveFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProjectileRemoveFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

projectileId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startProjectileRemoveFx(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProjectileId(builder:flatbuffers.Builder, projectileId:number) {
  builder.addFieldInt32(0, projectileId, 0);
}

static endProjectileRemoveFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProjectileRemoveFx(builder:flatbuffers.Builder, projectileId:number):flatbuffers.Offset {
  ProjectileRemoveFx.startProjectileRemoveFx(builder);
  ProjectileRemoveFx.addProjectileId(builder, projectileId);
  return ProjectileRemoveFx.endProjectileRemoveFx(builder);
}

unpack(): ProjectileRemoveFxT {
  return new ProjectileRemoveFxT(
    this.projectileId()
  );
}


unpackTo(_o: ProjectileRemoveFxT): void {
  _o.projectileId = this.projectileId();
}
}

export class ProjectileRemoveFxT implements flatbuffers.IGeneratedObject {
constructor(
  public projectileId: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ProjectileRemoveFx.createProjectileRemoveFx(builder,
    this.projectileId
  );
}
}
