// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ProjectileSpawnFx implements flatbuffers.IUnpackableObject<ProjectileSpawnFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProjectileSpawnFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProjectileSpawnFx(bb:flatbuffers.ByteBuffer, obj?:ProjectileSpawnFx):ProjectileSpawnFx {
  return (obj || new ProjectileSpawnFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProjectileSpawnFx(bb:flatbuffers.ByteBuffer, obj?:ProjectileSpawnFx):ProjectileSpawnFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProjectileSpawnFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

shotSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

projectileId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

posXQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

posYQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

posZQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

velXQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

velYQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

velZQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

ttlQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startProjectileSpawnFx(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt8(1, weaponSlot, 0);
}

static addShotSeq(builder:flatbuffers.Builder, shotSeq:number) {
  builder.addFieldInt32(2, shotSeq, 0);
}

static addProjectileId(builder:flatbuffers.Builder, projectileId:number) {
  builder.addFieldInt32(3, projectileId, 0);
}

static addPosXQ(builder:flatbuffers.Builder, posXQ:number) {
  builder.addFieldInt16(4, posXQ, 0);
}

static addPosYQ(builder:flatbuffers.Builder, posYQ:number) {
  builder.addFieldInt16(5, posYQ, 0);
}

static addPosZQ(builder:flatbuffers.Builder, posZQ:number) {
  builder.addFieldInt16(6, posZQ, 0);
}

static addVelXQ(builder:flatbuffers.Builder, velXQ:number) {
  builder.addFieldInt16(7, velXQ, 0);
}

static addVelYQ(builder:flatbuffers.Builder, velYQ:number) {
  builder.addFieldInt16(8, velYQ, 0);
}

static addVelZQ(builder:flatbuffers.Builder, velZQ:number) {
  builder.addFieldInt16(9, velZQ, 0);
}

static addTtlQ(builder:flatbuffers.Builder, ttlQ:number) {
  builder.addFieldInt16(10, ttlQ, 0);
}

static endProjectileSpawnFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProjectileSpawnFx(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponSlot:number, shotSeq:number, projectileId:number, posXQ:number, posYQ:number, posZQ:number, velXQ:number, velYQ:number, velZQ:number, ttlQ:number):flatbuffers.Offset {
  ProjectileSpawnFx.startProjectileSpawnFx(builder);
  ProjectileSpawnFx.addShooterId(builder, shooterIdOffset);
  ProjectileSpawnFx.addWeaponSlot(builder, weaponSlot);
  ProjectileSpawnFx.addShotSeq(builder, shotSeq);
  ProjectileSpawnFx.addProjectileId(builder, projectileId);
  ProjectileSpawnFx.addPosXQ(builder, posXQ);
  ProjectileSpawnFx.addPosYQ(builder, posYQ);
  ProjectileSpawnFx.addPosZQ(builder, posZQ);
  ProjectileSpawnFx.addVelXQ(builder, velXQ);
  ProjectileSpawnFx.addVelYQ(builder, velYQ);
  ProjectileSpawnFx.addVelZQ(builder, velZQ);
  ProjectileSpawnFx.addTtlQ(builder, ttlQ);
  return ProjectileSpawnFx.endProjectileSpawnFx(builder);
}

unpack(): ProjectileSpawnFxT {
  return new ProjectileSpawnFxT(
    this.shooterId(),
    this.weaponSlot(),
    this.shotSeq(),
    this.projectileId(),
    this.posXQ(),
    this.posYQ(),
    this.posZQ(),
    this.velXQ(),
    this.velYQ(),
    this.velZQ(),
    this.ttlQ()
  );
}


unpackTo(_o: ProjectileSpawnFxT): void {
  _o.shooterId = this.shooterId();
  _o.weaponSlot = this.weaponSlot();
  _o.shotSeq = this.shotSeq();
  _o.projectileId = this.projectileId();
  _o.posXQ = this.posXQ();
  _o.posYQ = this.posYQ();
  _o.posZQ = this.posZQ();
  _o.velXQ = this.velXQ();
  _o.velYQ = this.velYQ();
  _o.velZQ = this.velZQ();
  _o.ttlQ = this.ttlQ();
}
}

export class ProjectileSpawnFxT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public shotSeq: number = 0,
  public projectileId: number = 0,
  public posXQ: number = 0,
  public posYQ: number = 0,
  public posZQ: number = 0,
  public velXQ: number = 0,
  public velYQ: number = 0,
  public velZQ: number = 0,
  public ttlQ: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);

  return ProjectileSpawnFx.createProjectileSpawnFx(builder,
    shooterId,
    this.weaponSlot,
    this.shotSeq,
    this.projectileId,
    this.posXQ,
    this.posYQ,
    this.posZQ,
    this.velXQ,
    this.velYQ,
    this.velZQ,
    this.ttlQ
  );
}
}
