// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ServerHello implements flatbuffers.IUnpackableObject<ServerHelloT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerHello {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerHello(bb:flatbuffers.ByteBuffer, obj?:ServerHello):ServerHello {
  return (obj || new ServerHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerHello(bb:flatbuffers.ByteBuffer, obj?:ServerHello):ServerHello {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

protocolVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

connectionId():string|null
connectionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
connectionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

clientId():string|null
clientId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clientId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

serverTickRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

snapshotRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

snapshotKeyframeInterval():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

motd():string|null
motd(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
motd(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

connectionNonce():string|null
connectionNonce(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
connectionNonce(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startServerHello(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addProtocolVersion(builder:flatbuffers.Builder, protocolVersion:number) {
  builder.addFieldInt16(0, protocolVersion, 0);
}

static addConnectionId(builder:flatbuffers.Builder, connectionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, connectionIdOffset, 0);
}

static addClientId(builder:flatbuffers.Builder, clientIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, clientIdOffset, 0);
}

static addServerTickRate(builder:flatbuffers.Builder, serverTickRate:number) {
  builder.addFieldInt16(3, serverTickRate, 0);
}

static addSnapshotRate(builder:flatbuffers.Builder, snapshotRate:number) {
  builder.addFieldInt16(4, snapshotRate, 0);
}

static addSnapshotKeyframeInterval(builder:flatbuffers.Builder, snapshotKeyframeInterval:number) {
  builder.addFieldInt16(5, snapshotKeyframeInterval, 0);
}

static addMotd(builder:flatbuffers.Builder, motdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, motdOffset, 0);
}

static addConnectionNonce(builder:flatbuffers.Builder, connectionNonceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, connectionNonceOffset, 0);
}

static endServerHello(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createServerHello(builder:flatbuffers.Builder, protocolVersion:number, connectionIdOffset:flatbuffers.Offset, clientIdOffset:flatbuffers.Offset, serverTickRate:number, snapshotRate:number, snapshotKeyframeInterval:number, motdOffset:flatbuffers.Offset, connectionNonceOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServerHello.startServerHello(builder);
  ServerHello.addProtocolVersion(builder, protocolVersion);
  ServerHello.addConnectionId(builder, connectionIdOffset);
  ServerHello.addClientId(builder, clientIdOffset);
  ServerHello.addServerTickRate(builder, serverTickRate);
  ServerHello.addSnapshotRate(builder, snapshotRate);
  ServerHello.addSnapshotKeyframeInterval(builder, snapshotKeyframeInterval);
  ServerHello.addMotd(builder, motdOffset);
  ServerHello.addConnectionNonce(builder, connectionNonceOffset);
  return ServerHello.endServerHello(builder);
}

unpack(): ServerHelloT {
  return new ServerHelloT(
    this.protocolVersion(),
    this.connectionId(),
    this.clientId(),
    this.serverTickRate(),
    this.snapshotRate(),
    this.snapshotKeyframeInterval(),
    this.motd(),
    this.connectionNonce()
  );
}


unpackTo(_o: ServerHelloT): void {
  _o.protocolVersion = this.protocolVersion();
  _o.connectionId = this.connectionId();
  _o.clientId = this.clientId();
  _o.serverTickRate = this.serverTickRate();
  _o.snapshotRate = this.snapshotRate();
  _o.snapshotKeyframeInterval = this.snapshotKeyframeInterval();
  _o.motd = this.motd();
  _o.connectionNonce = this.connectionNonce();
}
}

export class ServerHelloT implements flatbuffers.IGeneratedObject {
constructor(
  public protocolVersion: number = 0,
  public connectionId: string|Uint8Array|null = null,
  public clientId: string|Uint8Array|null = null,
  public serverTickRate: number = 0,
  public snapshotRate: number = 0,
  public snapshotKeyframeInterval: number = 0,
  public motd: string|Uint8Array|null = null,
  public connectionNonce: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const connectionId = (this.connectionId !== null ? builder.createString(this.connectionId!) : 0);
  const clientId = (this.clientId !== null ? builder.createString(this.clientId!) : 0);
  const motd = (this.motd !== null ? builder.createString(this.motd!) : 0);
  const connectionNonce = (this.connectionNonce !== null ? builder.createString(this.connectionNonce!) : 0);

  return ServerHello.createServerHello(builder,
    this.protocolVersion,
    connectionId,
    clientId,
    this.serverTickRate,
    this.snapshotRate,
    this.snapshotKeyframeInterval,
    motd,
    connectionNonce
  );
}
}
