// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class SetLoadoutRequest implements flatbuffers.IUnpackableObject<SetLoadoutRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetLoadoutRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetLoadoutRequest(bb:flatbuffers.ByteBuffer, obj?:SetLoadoutRequest):SetLoadoutRequest {
  return (obj || new SetLoadoutRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetLoadoutRequest(bb:flatbuffers.ByteBuffer, obj?:SetLoadoutRequest):SetLoadoutRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetLoadoutRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

loadoutBits():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startSetLoadoutRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLoadoutBits(builder:flatbuffers.Builder, loadoutBits:number) {
  builder.addFieldInt32(0, loadoutBits, 0);
}

static endSetLoadoutRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetLoadoutRequest(builder:flatbuffers.Builder, loadoutBits:number):flatbuffers.Offset {
  SetLoadoutRequest.startSetLoadoutRequest(builder);
  SetLoadoutRequest.addLoadoutBits(builder, loadoutBits);
  return SetLoadoutRequest.endSetLoadoutRequest(builder);
}

unpack(): SetLoadoutRequestT {
  return new SetLoadoutRequestT(
    this.loadoutBits()
  );
}


unpackTo(_o: SetLoadoutRequestT): void {
  _o.loadoutBits = this.loadoutBits();
}
}

export class SetLoadoutRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public loadoutBits: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return SetLoadoutRequest.createSetLoadoutRequest(builder,
    this.loadoutBits
  );
}
}
