// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ShotFiredFx implements flatbuffers.IUnpackableObject<ShotFiredFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ShotFiredFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsShotFiredFx(bb:flatbuffers.ByteBuffer, obj?:ShotFiredFx):ShotFiredFx {
  return (obj || new ShotFiredFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsShotFiredFx(bb:flatbuffers.ByteBuffer, obj?:ShotFiredFx):ShotFiredFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ShotFiredFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

shotSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dryFire():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startShotFiredFx(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt8(1, weaponSlot, 0);
}

static addShotSeq(builder:flatbuffers.Builder, shotSeq:number) {
  builder.addFieldInt32(2, shotSeq, 0);
}

static addDryFire(builder:flatbuffers.Builder, dryFire:boolean) {
  builder.addFieldInt8(3, +dryFire, +false);
}

static endShotFiredFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createShotFiredFx(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponSlot:number, shotSeq:number, dryFire:boolean):flatbuffers.Offset {
  ShotFiredFx.startShotFiredFx(builder);
  ShotFiredFx.addShooterId(builder, shooterIdOffset);
  ShotFiredFx.addWeaponSlot(builder, weaponSlot);
  ShotFiredFx.addShotSeq(builder, shotSeq);
  ShotFiredFx.addDryFire(builder, dryFire);
  return ShotFiredFx.endShotFiredFx(builder);
}

unpack(): ShotFiredFxT {
  return new ShotFiredFxT(
    this.shooterId(),
    this.weaponSlot(),
    this.shotSeq(),
    this.dryFire()
  );
}


unpackTo(_o: ShotFiredFxT): void {
  _o.shooterId = this.shooterId();
  _o.weaponSlot = this.weaponSlot();
  _o.shotSeq = this.shotSeq();
  _o.dryFire = this.dryFire();
}
}

export class ShotFiredFxT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public shotSeq: number = 0,
  public dryFire: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);

  return ShotFiredFx.createShotFiredFx(builder,
    shooterId,
    this.weaponSlot,
    this.shotSeq,
    this.dryFire
  );
}
}
