// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { HitKind } from '../../afps/protocol/hit-kind.js';
import { SurfaceType } from '../../afps/protocol/surface-type.js';


export class ShotTraceFx implements flatbuffers.IUnpackableObject<ShotTraceFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ShotTraceFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsShotTraceFx(bb:flatbuffers.ByteBuffer, obj?:ShotTraceFx):ShotTraceFx {
  return (obj || new ShotTraceFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsShotTraceFx(bb:flatbuffers.ByteBuffer, obj?:ShotTraceFx):ShotTraceFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ShotTraceFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

shotSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dirOctX():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

dirOctY():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

hitDistQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

hitKind():HitKind {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : HitKind.None;
}

surfaceType():SurfaceType {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SurfaceType.Stone;
}

normalOctX():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

normalOctY():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

showTracer():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hitPosXQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

hitPosYQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

hitPosZQ():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startShotTraceFx(builder:flatbuffers.Builder) {
  builder.startObject(14);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt8(1, weaponSlot, 0);
}

static addShotSeq(builder:flatbuffers.Builder, shotSeq:number) {
  builder.addFieldInt32(2, shotSeq, 0);
}

static addDirOctX(builder:flatbuffers.Builder, dirOctX:number) {
  builder.addFieldInt16(3, dirOctX, 0);
}

static addDirOctY(builder:flatbuffers.Builder, dirOctY:number) {
  builder.addFieldInt16(4, dirOctY, 0);
}

static addHitDistQ(builder:flatbuffers.Builder, hitDistQ:number) {
  builder.addFieldInt16(5, hitDistQ, 0);
}

static addHitKind(builder:flatbuffers.Builder, hitKind:HitKind) {
  builder.addFieldInt8(6, hitKind, HitKind.None);
}

static addSurfaceType(builder:flatbuffers.Builder, surfaceType:SurfaceType) {
  builder.addFieldInt8(7, surfaceType, SurfaceType.Stone);
}

static addNormalOctX(builder:flatbuffers.Builder, normalOctX:number) {
  builder.addFieldInt16(8, normalOctX, 0);
}

static addNormalOctY(builder:flatbuffers.Builder, normalOctY:number) {
  builder.addFieldInt16(9, normalOctY, 0);
}

static addShowTracer(builder:flatbuffers.Builder, showTracer:boolean) {
  builder.addFieldInt8(10, +showTracer, +false);
}

static addHitPosXQ(builder:flatbuffers.Builder, hitPosXQ:number) {
  builder.addFieldInt16(11, hitPosXQ, 0);
}

static addHitPosYQ(builder:flatbuffers.Builder, hitPosYQ:number) {
  builder.addFieldInt16(12, hitPosYQ, 0);
}

static addHitPosZQ(builder:flatbuffers.Builder, hitPosZQ:number) {
  builder.addFieldInt16(13, hitPosZQ, 0);
}

static endShotTraceFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createShotTraceFx(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponSlot:number, shotSeq:number, dirOctX:number, dirOctY:number, hitDistQ:number, hitKind:HitKind, surfaceType:SurfaceType, normalOctX:number, normalOctY:number, showTracer:boolean, hitPosXQ:number, hitPosYQ:number, hitPosZQ:number):flatbuffers.Offset {
  ShotTraceFx.startShotTraceFx(builder);
  ShotTraceFx.addShooterId(builder, shooterIdOffset);
  ShotTraceFx.addWeaponSlot(builder, weaponSlot);
  ShotTraceFx.addShotSeq(builder, shotSeq);
  ShotTraceFx.addDirOctX(builder, dirOctX);
  ShotTraceFx.addDirOctY(builder, dirOctY);
  ShotTraceFx.addHitDistQ(builder, hitDistQ);
  ShotTraceFx.addHitKind(builder, hitKind);
  ShotTraceFx.addSurfaceType(builder, surfaceType);
  ShotTraceFx.addNormalOctX(builder, normalOctX);
  ShotTraceFx.addNormalOctY(builder, normalOctY);
  ShotTraceFx.addShowTracer(builder, showTracer);
  ShotTraceFx.addHitPosXQ(builder, hitPosXQ);
  ShotTraceFx.addHitPosYQ(builder, hitPosYQ);
  ShotTraceFx.addHitPosZQ(builder, hitPosZQ);
  return ShotTraceFx.endShotTraceFx(builder);
}

unpack(): ShotTraceFxT {
  return new ShotTraceFxT(
    this.shooterId(),
    this.weaponSlot(),
    this.shotSeq(),
    this.dirOctX(),
    this.dirOctY(),
    this.hitDistQ(),
    this.hitKind(),
    this.surfaceType(),
    this.normalOctX(),
    this.normalOctY(),
    this.showTracer(),
    this.hitPosXQ(),
    this.hitPosYQ(),
    this.hitPosZQ()
  );
}


unpackTo(_o: ShotTraceFxT): void {
  _o.shooterId = this.shooterId();
  _o.weaponSlot = this.weaponSlot();
  _o.shotSeq = this.shotSeq();
  _o.dirOctX = this.dirOctX();
  _o.dirOctY = this.dirOctY();
  _o.hitDistQ = this.hitDistQ();
  _o.hitKind = this.hitKind();
  _o.surfaceType = this.surfaceType();
  _o.normalOctX = this.normalOctX();
  _o.normalOctY = this.normalOctY();
  _o.showTracer = this.showTracer();
  _o.hitPosXQ = this.hitPosXQ();
  _o.hitPosYQ = this.hitPosYQ();
  _o.hitPosZQ = this.hitPosZQ();
}
}

export class ShotTraceFxT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public shotSeq: number = 0,
  public dirOctX: number = 0,
  public dirOctY: number = 0,
  public hitDistQ: number = 0,
  public hitKind: HitKind = HitKind.None,
  public surfaceType: SurfaceType = SurfaceType.Stone,
  public normalOctX: number = 0,
  public normalOctY: number = 0,
  public showTracer: boolean = false,
  public hitPosXQ: number = 0,
  public hitPosYQ: number = 0,
  public hitPosZQ: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);

  return ShotTraceFx.createShotTraceFx(builder,
    shooterId,
    this.weaponSlot,
    this.shotSeq,
    this.dirOctX,
    this.dirOctY,
    this.hitDistQ,
    this.hitKind,
    this.surfaceType,
    this.normalOctX,
    this.normalOctY,
    this.showTracer,
    this.hitPosXQ,
    this.hitPosYQ,
    this.hitPosZQ
  );
}
}
