// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class StateSnapshotDelta implements flatbuffers.IUnpackableObject<StateSnapshotDeltaT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StateSnapshotDelta {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStateSnapshotDelta(bb:flatbuffers.ByteBuffer, obj?:StateSnapshotDelta):StateSnapshotDelta {
  return (obj || new StateSnapshotDelta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStateSnapshotDelta(bb:flatbuffers.ByteBuffer, obj?:StateSnapshotDelta):StateSnapshotDelta {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateSnapshotDelta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

serverTick():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

baseTick():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

lastProcessedInputSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mask():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

clientId():string|null
clientId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clientId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

posX():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

posY():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

posZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

velX():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

velY():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

velZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dashCooldown():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

health():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

kills():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

deaths():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startStateSnapshotDelta(builder:flatbuffers.Builder) {
  builder.startObject(16);
}

static addServerTick(builder:flatbuffers.Builder, serverTick:number) {
  builder.addFieldInt32(0, serverTick, 0);
}

static addBaseTick(builder:flatbuffers.Builder, baseTick:number) {
  builder.addFieldInt32(1, baseTick, 0);
}

static addLastProcessedInputSeq(builder:flatbuffers.Builder, lastProcessedInputSeq:number) {
  builder.addFieldInt32(2, lastProcessedInputSeq, 0);
}

static addMask(builder:flatbuffers.Builder, mask:number) {
  builder.addFieldInt32(3, mask, 0);
}

static addClientId(builder:flatbuffers.Builder, clientIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, clientIdOffset, 0);
}

static addPosX(builder:flatbuffers.Builder, posX:number) {
  builder.addFieldFloat64(5, posX, 0.0);
}

static addPosY(builder:flatbuffers.Builder, posY:number) {
  builder.addFieldFloat64(6, posY, 0.0);
}

static addPosZ(builder:flatbuffers.Builder, posZ:number) {
  builder.addFieldFloat64(7, posZ, 0.0);
}

static addVelX(builder:flatbuffers.Builder, velX:number) {
  builder.addFieldFloat64(8, velX, 0.0);
}

static addVelY(builder:flatbuffers.Builder, velY:number) {
  builder.addFieldFloat64(9, velY, 0.0);
}

static addVelZ(builder:flatbuffers.Builder, velZ:number) {
  builder.addFieldFloat64(10, velZ, 0.0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt32(11, weaponSlot, 0);
}

static addDashCooldown(builder:flatbuffers.Builder, dashCooldown:number) {
  builder.addFieldFloat64(12, dashCooldown, 0.0);
}

static addHealth(builder:flatbuffers.Builder, health:number) {
  builder.addFieldFloat64(13, health, 0.0);
}

static addKills(builder:flatbuffers.Builder, kills:number) {
  builder.addFieldInt32(14, kills, 0);
}

static addDeaths(builder:flatbuffers.Builder, deaths:number) {
  builder.addFieldInt32(15, deaths, 0);
}

static endStateSnapshotDelta(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStateSnapshotDelta(builder:flatbuffers.Builder, serverTick:number, baseTick:number, lastProcessedInputSeq:number, mask:number, clientIdOffset:flatbuffers.Offset, posX:number, posY:number, posZ:number, velX:number, velY:number, velZ:number, weaponSlot:number, dashCooldown:number, health:number, kills:number, deaths:number):flatbuffers.Offset {
  StateSnapshotDelta.startStateSnapshotDelta(builder);
  StateSnapshotDelta.addServerTick(builder, serverTick);
  StateSnapshotDelta.addBaseTick(builder, baseTick);
  StateSnapshotDelta.addLastProcessedInputSeq(builder, lastProcessedInputSeq);
  StateSnapshotDelta.addMask(builder, mask);
  StateSnapshotDelta.addClientId(builder, clientIdOffset);
  StateSnapshotDelta.addPosX(builder, posX);
  StateSnapshotDelta.addPosY(builder, posY);
  StateSnapshotDelta.addPosZ(builder, posZ);
  StateSnapshotDelta.addVelX(builder, velX);
  StateSnapshotDelta.addVelY(builder, velY);
  StateSnapshotDelta.addVelZ(builder, velZ);
  StateSnapshotDelta.addWeaponSlot(builder, weaponSlot);
  StateSnapshotDelta.addDashCooldown(builder, dashCooldown);
  StateSnapshotDelta.addHealth(builder, health);
  StateSnapshotDelta.addKills(builder, kills);
  StateSnapshotDelta.addDeaths(builder, deaths);
  return StateSnapshotDelta.endStateSnapshotDelta(builder);
}

unpack(): StateSnapshotDeltaT {
  return new StateSnapshotDeltaT(
    this.serverTick(),
    this.baseTick(),
    this.lastProcessedInputSeq(),
    this.mask(),
    this.clientId(),
    this.posX(),
    this.posY(),
    this.posZ(),
    this.velX(),
    this.velY(),
    this.velZ(),
    this.weaponSlot(),
    this.dashCooldown(),
    this.health(),
    this.kills(),
    this.deaths()
  );
}


unpackTo(_o: StateSnapshotDeltaT): void {
  _o.serverTick = this.serverTick();
  _o.baseTick = this.baseTick();
  _o.lastProcessedInputSeq = this.lastProcessedInputSeq();
  _o.mask = this.mask();
  _o.clientId = this.clientId();
  _o.posX = this.posX();
  _o.posY = this.posY();
  _o.posZ = this.posZ();
  _o.velX = this.velX();
  _o.velY = this.velY();
  _o.velZ = this.velZ();
  _o.weaponSlot = this.weaponSlot();
  _o.dashCooldown = this.dashCooldown();
  _o.health = this.health();
  _o.kills = this.kills();
  _o.deaths = this.deaths();
}
}

export class StateSnapshotDeltaT implements flatbuffers.IGeneratedObject {
constructor(
  public serverTick: number = 0,
  public baseTick: number = 0,
  public lastProcessedInputSeq: number = 0,
  public mask: number = 0,
  public clientId: string|Uint8Array|null = null,
  public posX: number = 0.0,
  public posY: number = 0.0,
  public posZ: number = 0.0,
  public velX: number = 0.0,
  public velY: number = 0.0,
  public velZ: number = 0.0,
  public weaponSlot: number = 0,
  public dashCooldown: number = 0.0,
  public health: number = 0.0,
  public kills: number = 0,
  public deaths: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const clientId = (this.clientId !== null ? builder.createString(this.clientId!) : 0);

  return StateSnapshotDelta.createStateSnapshotDelta(builder,
    this.serverTick,
    this.baseTick,
    this.lastProcessedInputSeq,
    this.mask,
    clientId,
    this.posX,
    this.posY,
    this.posZ,
    this.velX,
    this.velY,
    this.velZ,
    this.weaponSlot,
    this.dashCooldown,
    this.health,
    this.kills,
    this.deaths
  );
}
}
