// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SurfaceType {
  Stone = 0,
  Metal = 1,
  Dirt = 2,
  Energy = 3
}
