// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class VentFx implements flatbuffers.IUnpackableObject<VentFxT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VentFx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVentFx(bb:flatbuffers.ByteBuffer, obj?:VentFx):VentFx {
  return (obj || new VentFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVentFx(bb:flatbuffers.ByteBuffer, obj?:VentFx):VentFx {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VentFx()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startVentFx(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt8(1, weaponSlot, 0);
}

static endVentFx(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVentFx(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponSlot:number):flatbuffers.Offset {
  VentFx.startVentFx(builder);
  VentFx.addShooterId(builder, shooterIdOffset);
  VentFx.addWeaponSlot(builder, weaponSlot);
  return VentFx.endVentFx(builder);
}

unpack(): VentFxT {
  return new VentFxT(
    this.shooterId(),
    this.weaponSlot()
  );
}


unpackTo(_o: VentFxT): void {
  _o.shooterId = this.shooterId();
  _o.weaponSlot = this.weaponSlot();
}
}

export class VentFxT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponSlot: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);

  return VentFx.createVentFx(builder,
    shooterId,
    this.weaponSlot
  );
}
}
