// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class WeaponFiredEvent implements flatbuffers.IUnpackableObject<WeaponFiredEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WeaponFiredEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWeaponFiredEvent(bb:flatbuffers.ByteBuffer, obj?:WeaponFiredEvent):WeaponFiredEvent {
  return (obj || new WeaponFiredEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWeaponFiredEvent(bb:flatbuffers.ByteBuffer, obj?:WeaponFiredEvent):WeaponFiredEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WeaponFiredEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponId():string|null
weaponId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weaponId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

serverTick():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

shotSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

muzzlePosX():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

muzzlePosY():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

muzzlePosZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dirX():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dirY():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dirZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

dryFire():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

casingEnabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

casingPosX():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingPosY():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingPosZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingRotX():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingRotY():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingRotZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingVelX():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingVelY():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingVelZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingAngX():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingAngY():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingAngZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

casingSeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startWeaponFiredEvent(builder:flatbuffers.Builder) {
  builder.startObject(26);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponId(builder:flatbuffers.Builder, weaponIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, weaponIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt32(2, weaponSlot, 0);
}

static addServerTick(builder:flatbuffers.Builder, serverTick:number) {
  builder.addFieldInt32(3, serverTick, 0);
}

static addShotSeq(builder:flatbuffers.Builder, shotSeq:number) {
  builder.addFieldInt32(4, shotSeq, 0);
}

static addMuzzlePosX(builder:flatbuffers.Builder, muzzlePosX:number) {
  builder.addFieldFloat64(5, muzzlePosX, 0.0);
}

static addMuzzlePosY(builder:flatbuffers.Builder, muzzlePosY:number) {
  builder.addFieldFloat64(6, muzzlePosY, 0.0);
}

static addMuzzlePosZ(builder:flatbuffers.Builder, muzzlePosZ:number) {
  builder.addFieldFloat64(7, muzzlePosZ, 0.0);
}

static addDirX(builder:flatbuffers.Builder, dirX:number) {
  builder.addFieldFloat64(8, dirX, 0.0);
}

static addDirY(builder:flatbuffers.Builder, dirY:number) {
  builder.addFieldFloat64(9, dirY, 0.0);
}

static addDirZ(builder:flatbuffers.Builder, dirZ:number) {
  builder.addFieldFloat64(10, dirZ, 0.0);
}

static addDryFire(builder:flatbuffers.Builder, dryFire:boolean) {
  builder.addFieldInt8(11, +dryFire, +false);
}

static addCasingEnabled(builder:flatbuffers.Builder, casingEnabled:boolean) {
  builder.addFieldInt8(12, +casingEnabled, +false);
}

static addCasingPosX(builder:flatbuffers.Builder, casingPosX:number) {
  builder.addFieldFloat64(13, casingPosX, 0.0);
}

static addCasingPosY(builder:flatbuffers.Builder, casingPosY:number) {
  builder.addFieldFloat64(14, casingPosY, 0.0);
}

static addCasingPosZ(builder:flatbuffers.Builder, casingPosZ:number) {
  builder.addFieldFloat64(15, casingPosZ, 0.0);
}

static addCasingRotX(builder:flatbuffers.Builder, casingRotX:number) {
  builder.addFieldFloat64(16, casingRotX, 0.0);
}

static addCasingRotY(builder:flatbuffers.Builder, casingRotY:number) {
  builder.addFieldFloat64(17, casingRotY, 0.0);
}

static addCasingRotZ(builder:flatbuffers.Builder, casingRotZ:number) {
  builder.addFieldFloat64(18, casingRotZ, 0.0);
}

static addCasingVelX(builder:flatbuffers.Builder, casingVelX:number) {
  builder.addFieldFloat64(19, casingVelX, 0.0);
}

static addCasingVelY(builder:flatbuffers.Builder, casingVelY:number) {
  builder.addFieldFloat64(20, casingVelY, 0.0);
}

static addCasingVelZ(builder:flatbuffers.Builder, casingVelZ:number) {
  builder.addFieldFloat64(21, casingVelZ, 0.0);
}

static addCasingAngX(builder:flatbuffers.Builder, casingAngX:number) {
  builder.addFieldFloat64(22, casingAngX, 0.0);
}

static addCasingAngY(builder:flatbuffers.Builder, casingAngY:number) {
  builder.addFieldFloat64(23, casingAngY, 0.0);
}

static addCasingAngZ(builder:flatbuffers.Builder, casingAngZ:number) {
  builder.addFieldFloat64(24, casingAngZ, 0.0);
}

static addCasingSeed(builder:flatbuffers.Builder, casingSeed:number) {
  builder.addFieldInt32(25, casingSeed, 0);
}

static endWeaponFiredEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWeaponFiredEvent(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponIdOffset:flatbuffers.Offset, weaponSlot:number, serverTick:number, shotSeq:number, muzzlePosX:number, muzzlePosY:number, muzzlePosZ:number, dirX:number, dirY:number, dirZ:number, dryFire:boolean, casingEnabled:boolean, casingPosX:number, casingPosY:number, casingPosZ:number, casingRotX:number, casingRotY:number, casingRotZ:number, casingVelX:number, casingVelY:number, casingVelZ:number, casingAngX:number, casingAngY:number, casingAngZ:number, casingSeed:number):flatbuffers.Offset {
  WeaponFiredEvent.startWeaponFiredEvent(builder);
  WeaponFiredEvent.addShooterId(builder, shooterIdOffset);
  WeaponFiredEvent.addWeaponId(builder, weaponIdOffset);
  WeaponFiredEvent.addWeaponSlot(builder, weaponSlot);
  WeaponFiredEvent.addServerTick(builder, serverTick);
  WeaponFiredEvent.addShotSeq(builder, shotSeq);
  WeaponFiredEvent.addMuzzlePosX(builder, muzzlePosX);
  WeaponFiredEvent.addMuzzlePosY(builder, muzzlePosY);
  WeaponFiredEvent.addMuzzlePosZ(builder, muzzlePosZ);
  WeaponFiredEvent.addDirX(builder, dirX);
  WeaponFiredEvent.addDirY(builder, dirY);
  WeaponFiredEvent.addDirZ(builder, dirZ);
  WeaponFiredEvent.addDryFire(builder, dryFire);
  WeaponFiredEvent.addCasingEnabled(builder, casingEnabled);
  WeaponFiredEvent.addCasingPosX(builder, casingPosX);
  WeaponFiredEvent.addCasingPosY(builder, casingPosY);
  WeaponFiredEvent.addCasingPosZ(builder, casingPosZ);
  WeaponFiredEvent.addCasingRotX(builder, casingRotX);
  WeaponFiredEvent.addCasingRotY(builder, casingRotY);
  WeaponFiredEvent.addCasingRotZ(builder, casingRotZ);
  WeaponFiredEvent.addCasingVelX(builder, casingVelX);
  WeaponFiredEvent.addCasingVelY(builder, casingVelY);
  WeaponFiredEvent.addCasingVelZ(builder, casingVelZ);
  WeaponFiredEvent.addCasingAngX(builder, casingAngX);
  WeaponFiredEvent.addCasingAngY(builder, casingAngY);
  WeaponFiredEvent.addCasingAngZ(builder, casingAngZ);
  WeaponFiredEvent.addCasingSeed(builder, casingSeed);
  return WeaponFiredEvent.endWeaponFiredEvent(builder);
}

unpack(): WeaponFiredEventT {
  return new WeaponFiredEventT(
    this.shooterId(),
    this.weaponId(),
    this.weaponSlot(),
    this.serverTick(),
    this.shotSeq(),
    this.muzzlePosX(),
    this.muzzlePosY(),
    this.muzzlePosZ(),
    this.dirX(),
    this.dirY(),
    this.dirZ(),
    this.dryFire(),
    this.casingEnabled(),
    this.casingPosX(),
    this.casingPosY(),
    this.casingPosZ(),
    this.casingRotX(),
    this.casingRotY(),
    this.casingRotZ(),
    this.casingVelX(),
    this.casingVelY(),
    this.casingVelZ(),
    this.casingAngX(),
    this.casingAngY(),
    this.casingAngZ(),
    this.casingSeed()
  );
}


unpackTo(_o: WeaponFiredEventT): void {
  _o.shooterId = this.shooterId();
  _o.weaponId = this.weaponId();
  _o.weaponSlot = this.weaponSlot();
  _o.serverTick = this.serverTick();
  _o.shotSeq = this.shotSeq();
  _o.muzzlePosX = this.muzzlePosX();
  _o.muzzlePosY = this.muzzlePosY();
  _o.muzzlePosZ = this.muzzlePosZ();
  _o.dirX = this.dirX();
  _o.dirY = this.dirY();
  _o.dirZ = this.dirZ();
  _o.dryFire = this.dryFire();
  _o.casingEnabled = this.casingEnabled();
  _o.casingPosX = this.casingPosX();
  _o.casingPosY = this.casingPosY();
  _o.casingPosZ = this.casingPosZ();
  _o.casingRotX = this.casingRotX();
  _o.casingRotY = this.casingRotY();
  _o.casingRotZ = this.casingRotZ();
  _o.casingVelX = this.casingVelX();
  _o.casingVelY = this.casingVelY();
  _o.casingVelZ = this.casingVelZ();
  _o.casingAngX = this.casingAngX();
  _o.casingAngY = this.casingAngY();
  _o.casingAngZ = this.casingAngZ();
  _o.casingSeed = this.casingSeed();
}
}

export class WeaponFiredEventT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public serverTick: number = 0,
  public shotSeq: number = 0,
  public muzzlePosX: number = 0.0,
  public muzzlePosY: number = 0.0,
  public muzzlePosZ: number = 0.0,
  public dirX: number = 0.0,
  public dirY: number = 0.0,
  public dirZ: number = 0.0,
  public dryFire: boolean = false,
  public casingEnabled: boolean = false,
  public casingPosX: number = 0.0,
  public casingPosY: number = 0.0,
  public casingPosZ: number = 0.0,
  public casingRotX: number = 0.0,
  public casingRotY: number = 0.0,
  public casingRotZ: number = 0.0,
  public casingVelX: number = 0.0,
  public casingVelY: number = 0.0,
  public casingVelZ: number = 0.0,
  public casingAngX: number = 0.0,
  public casingAngY: number = 0.0,
  public casingAngZ: number = 0.0,
  public casingSeed: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);
  const weaponId = (this.weaponId !== null ? builder.createString(this.weaponId!) : 0);

  return WeaponFiredEvent.createWeaponFiredEvent(builder,
    shooterId,
    weaponId,
    this.weaponSlot,
    this.serverTick,
    this.shotSeq,
    this.muzzlePosX,
    this.muzzlePosY,
    this.muzzlePosZ,
    this.dirX,
    this.dirY,
    this.dirZ,
    this.dryFire,
    this.casingEnabled,
    this.casingPosX,
    this.casingPosY,
    this.casingPosZ,
    this.casingRotX,
    this.casingRotY,
    this.casingRotZ,
    this.casingVelX,
    this.casingVelY,
    this.casingVelZ,
    this.casingAngX,
    this.casingAngY,
    this.casingAngZ,
    this.casingSeed
  );
}
}
