// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class WeaponReloadEvent implements flatbuffers.IUnpackableObject<WeaponReloadEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WeaponReloadEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWeaponReloadEvent(bb:flatbuffers.ByteBuffer, obj?:WeaponReloadEvent):WeaponReloadEvent {
  return (obj || new WeaponReloadEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWeaponReloadEvent(bb:flatbuffers.ByteBuffer, obj?:WeaponReloadEvent):WeaponReloadEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WeaponReloadEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shooterId():string|null
shooterId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shooterId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponId():string|null
weaponId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weaponId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weaponSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

serverTick():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

reloadSeconds():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startWeaponReloadEvent(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addShooterId(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shooterIdOffset, 0);
}

static addWeaponId(builder:flatbuffers.Builder, weaponIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, weaponIdOffset, 0);
}

static addWeaponSlot(builder:flatbuffers.Builder, weaponSlot:number) {
  builder.addFieldInt32(2, weaponSlot, 0);
}

static addServerTick(builder:flatbuffers.Builder, serverTick:number) {
  builder.addFieldInt32(3, serverTick, 0);
}

static addReloadSeconds(builder:flatbuffers.Builder, reloadSeconds:number) {
  builder.addFieldFloat64(4, reloadSeconds, 0.0);
}

static endWeaponReloadEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWeaponReloadEvent(builder:flatbuffers.Builder, shooterIdOffset:flatbuffers.Offset, weaponIdOffset:flatbuffers.Offset, weaponSlot:number, serverTick:number, reloadSeconds:number):flatbuffers.Offset {
  WeaponReloadEvent.startWeaponReloadEvent(builder);
  WeaponReloadEvent.addShooterId(builder, shooterIdOffset);
  WeaponReloadEvent.addWeaponId(builder, weaponIdOffset);
  WeaponReloadEvent.addWeaponSlot(builder, weaponSlot);
  WeaponReloadEvent.addServerTick(builder, serverTick);
  WeaponReloadEvent.addReloadSeconds(builder, reloadSeconds);
  return WeaponReloadEvent.endWeaponReloadEvent(builder);
}

unpack(): WeaponReloadEventT {
  return new WeaponReloadEventT(
    this.shooterId(),
    this.weaponId(),
    this.weaponSlot(),
    this.serverTick(),
    this.reloadSeconds()
  );
}


unpackTo(_o: WeaponReloadEventT): void {
  _o.shooterId = this.shooterId();
  _o.weaponId = this.weaponId();
  _o.weaponSlot = this.weaponSlot();
  _o.serverTick = this.serverTick();
  _o.reloadSeconds = this.reloadSeconds();
}
}

export class WeaponReloadEventT implements flatbuffers.IGeneratedObject {
constructor(
  public shooterId: string|Uint8Array|null = null,
  public weaponId: string|Uint8Array|null = null,
  public weaponSlot: number = 0,
  public serverTick: number = 0,
  public reloadSeconds: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shooterId = (this.shooterId !== null ? builder.createString(this.shooterId!) : 0);
  const weaponId = (this.weaponId !== null ? builder.createString(this.weaponId!) : 0);

  return WeaponReloadEvent.createWeaponReloadEvent(builder,
    shooterId,
    weaponId,
    this.weaponSlot,
    this.serverTick,
    this.reloadSeconds
  );
}
}
